name: fire_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.0
  json_annotation: ^4.8.1
  after_layout: ^1.2.0
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Geologica
      fonts:
        - asset: assets/fonts/geologica/Geologica_Auto-Thin.ttf
          weight: 100
        - asset: assets/fonts/geologica/Geologica_Auto-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/geologica/Geologica_Auto-Light.ttf
          weight: 300
        - asset: assets/fonts/geologica/Geologica_Auto-Regular.ttf
          weight: 400
        - asset: assets/fonts/geologica/Geologica_Auto-Medium.ttf
          weight: 500
        - asset: assets/fonts/geologica/Geologica_Auto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/geologica/Geologica_Auto-Bold.ttf
          weight: 700
        - asset: assets/fonts/geologica/Geologica_Auto-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/geologica/Geologica_Auto-Black.ttf
          weight: 900
